<<<<<<< HEAD
# Generated by Django 3.2.23 on 2024-05-03 11:10

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 3.2.23 on 2024-05-03 04:54

from django.db import migrations, models
>>>>>>> 4bfbcb56b6462682769115415376abce4fef6133


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20)),
                ('number_of_doors', models.PositiveIntegerField()),
                ('number_of_seats', models.PositiveIntegerField()),
                ('rental_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability_calendar', models.TextField()),
                ('special_offers', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('air_conditioning', models.BooleanField(default=False)),
                ('gps_navigation', models.BooleanField(default=False)),
                ('bluetooth_connectivity', models.BooleanField(default=False)),
                ('safety_features', models.TextField()),
                ('audio_system_details', models.TextField()),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('delivery_options', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poshcars.carbrand')),
                ('rental_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poshcars.rentalagency')),
=======
            name='RentalAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('car_make', models.CharField(max_length=50)),
                ('car_model', models.CharField(max_length=50)),
                ('year_of_manufacture', models.IntegerField(max_length=4)),
                ('milleage', models.FloatField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('number_of_seats', models.IntegerField(max_length=8)),
                ('number_of_doors', models.IntegerField(max_length=4)),
                ('car_reg_number', models.CharField(max_length=50)),
                ('daily_rental_rate', models.FloatField()),
                ('insurance', models.CharField(max_length=50)),
                ('car_image', models.ImageField(upload_to='media')),
                ('transmission_type', models.CharField(max_length=50)),
>>>>>>> 4bfbcb56b6462682769115415376abce4fef6133
            ],
        ),
    ]
