# Generated by Django 3.2.23 on 2024-05-03 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalauth',
            name='number_of_doors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalauth',
            name='number_of_seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalauth',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalauth',
            name='year_of_manufacture',
            field=models.IntegerField(),
        ),
    ]
