# Generated by Django 3.2.23 on 2024-05-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0003_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
