# Generated by Django 3.2.23 on 2024-05-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0004_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(choices=[(1, '1 Day'), (2, '2 Days'), (3, '3 Days'), (4, '4 Days'), (5, '5 Days')])),
                ('quantity', models.IntegerField(choices=[(1, '1 Day'), (2, '2 Days'), (3, '3 Days'), (4, '4 Days'), (5, '5 Days')])),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('cash', 'Cash')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
