# Generated by Django 3.2.23 on 2024-05-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0005_auto_20240507_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
