# Generated by Django 3.2.23 on 2024-05-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0006_alter_car_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='status',
            new_name='is_approved',
        ),
    ]
