# Generated by Django 3.2.23 on 2024-05-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0007_rename_status_rental_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_returned',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
