# Generated by Django 3.2.23 on 2024-05-07 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0007_rental_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poshcars.car'),
        ),
    ]
