# Generated by Django 3.2.23 on 2024-05-07 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0008_rental_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='startdate',
            field=models.DateField(null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
