# Generated by Django 3.2.23 on 2024-05-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0008_rental_is_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
