# Generated by Django 3.2.23 on 2024-05-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0009_rental_date_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='quantity',
        ),
    ]
