# Generated by Django 3.2.23 on 2024-05-07 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poshcars', '0010_alter_rental_startdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalauth',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rentalauth',
            name='milleage',
        ),
        migrations.RemoveField(
            model_name='rentalauth',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rentalauth',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='rentalauth',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='rentalauth',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
