# Generated by Django 3.2.23 on 2024-05-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0010_remove_rental_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
