# Generated by Django 3.2.23 on 2024-05-07 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0011_auto_20240507_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalauth',
            old_name='insurance',
            new_name='insurance_details',
        ),
    ]
