# Generated by Django 3.2.23 on 2024-05-07 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poshcars', '0012_rename_insurance_rentalauth_insurance_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalauth',
            old_name='car_image',
            new_name='photos',
        ),
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nin', models.CharField(max_length=20)),
                ('phonenumber', models.IntegerField()),
                ('drivers_license', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
