# Generated by Django 3.2.23 on 2024-05-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0012_rental_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='availability',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
