# Generated by Django 3.2.23 on 2024-05-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0013_auto_20240507_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
