# Generated by Django 3.2.23 on 2024-05-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0014_userdetails_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalauth',
            old_name='transmission_type',
            new_name='transmission',
        ),
    ]
