# Generated by Django 3.2.23 on 2024-05-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0015_rename_transmission_type_rentalauth_transmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rental_agency',
        ),
    ]
