# Generated by Django 3.2.23 on 2024-05-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0016_remove_car_rental_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='mileage',
        ),
    ]
