# Generated by Django 3.2.23 on 2024-05-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poshcars', '0018_auto_20240507_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
